apiVersion: v1
kind: Secret
metadata:
  name: obtrace-sdk
type: Opaque
stringData:
  OBTRACE_API_KEY: "REPLACE_WITH_YOUR_API_KEY"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: obtrace-sdk-config
data:
  OBTRACE_TENANT_ID: "tenant-prod"
  OBTRACE_PROJECT_ID: "project-prod"
  OBTRACE_ENV: "prod"
